### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by LukasBacigal** [packeteer/alpine-openldap#1]
```
VOLUME ["/srv/openldap/conf", "/etc/openldap"]
VOLUME ["/srv/openldap/data", "/var/lib/openldap"]
```

You are probably trying to load HostSystem:/srv/openldap/conf to Docker:/etc/openldap but be aware you can't do it via Dockerfile and you need it to load at runtime, more here:

http://stackoverflow.com/questions/26050899/how-to-mount-host-volumes-into-docker-containers-in-dockerfile-during-build

**Comment by packeteer** [comment]
thanks. I've removed and it builds now. still working on configs
